// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.26.1
// source: common/def/app.v1.proto

package def

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// App application
type App struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name app 名字
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// version app 版本
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// env app 环境
	Env string `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`
}

func (x *App) Reset() {
	*x = App{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_def_app_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_common_def_app_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_common_def_app_v1_proto_rawDescGZIP(), []int{0}
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *App) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

// Secret ...
type Secret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransferEncrypt *Secret_TransferEncrypt `protobuf:"bytes,1,opt,name=transfer_encrypt,json=transferEncrypt,proto3" json:"transfer_encrypt,omitempty"`
	ServiceEncrypt  *Secret_ServiceEncrypt  `protobuf:"bytes,2,opt,name=service_encrypt,json=serviceEncrypt,proto3" json:"service_encrypt,omitempty"`
	JwtEncrypt      *Secret_TokenEncrypt    `protobuf:"bytes,3,opt,name=jwt_encrypt,json=jwtEncrypt,proto3" json:"jwt_encrypt,omitempty"`
	RefreshEncrypt  *Secret_RefreshEncrypt  `protobuf:"bytes,4,opt,name=refresh_encrypt,json=refreshEncrypt,proto3" json:"refresh_encrypt,omitempty"`
}

func (x *Secret) Reset() {
	*x = Secret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_def_app_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_common_def_app_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_common_def_app_v1_proto_rawDescGZIP(), []int{1}
}

func (x *Secret) GetTransferEncrypt() *Secret_TransferEncrypt {
	if x != nil {
		return x.TransferEncrypt
	}
	return nil
}

func (x *Secret) GetServiceEncrypt() *Secret_ServiceEncrypt {
	if x != nil {
		return x.ServiceEncrypt
	}
	return nil
}

func (x *Secret) GetJwtEncrypt() *Secret_TokenEncrypt {
	if x != nil {
		return x.JwtEncrypt
	}
	return nil
}

func (x *Secret) GetRefreshEncrypt() *Secret_RefreshEncrypt {
	if x != nil {
		return x.RefreshEncrypt
	}
	return nil
}

// 非对称加密传输,主要用于密码传递等,防止传递过程中明文信息被log,导致泄露
type Secret_TransferEncrypt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey  string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey string `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (x *Secret_TransferEncrypt) Reset() {
	*x = Secret_TransferEncrypt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_def_app_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secret_TransferEncrypt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret_TransferEncrypt) ProtoMessage() {}

func (x *Secret_TransferEncrypt) ProtoReflect() protoreflect.Message {
	mi := &file_common_def_app_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret_TransferEncrypt.ProtoReflect.Descriptor instead.
func (*Secret_TransferEncrypt) Descriptor() ([]byte, []int) {
	return file_common_def_app_v1_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Secret_TransferEncrypt) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Secret_TransferEncrypt) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

// 非对称加密传输,主要用于服务请求鉴权,服务间的鉴权
type Secret_ServiceEncrypt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey  string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey string `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (x *Secret_ServiceEncrypt) Reset() {
	*x = Secret_ServiceEncrypt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_def_app_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secret_ServiceEncrypt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret_ServiceEncrypt) ProtoMessage() {}

func (x *Secret_ServiceEncrypt) ProtoReflect() protoreflect.Message {
	mi := &file_common_def_app_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret_ServiceEncrypt.ProtoReflect.Descriptor instead.
func (*Secret_ServiceEncrypt) Descriptor() ([]byte, []int) {
	return file_common_def_app_v1_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Secret_ServiceEncrypt) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Secret_ServiceEncrypt) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type Secret_TokenEncrypt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Secret_TokenEncrypt) Reset() {
	*x = Secret_TokenEncrypt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_def_app_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secret_TokenEncrypt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret_TokenEncrypt) ProtoMessage() {}

func (x *Secret_TokenEncrypt) ProtoReflect() protoreflect.Message {
	mi := &file_common_def_app_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret_TokenEncrypt.ProtoReflect.Descriptor instead.
func (*Secret_TokenEncrypt) Descriptor() ([]byte, []int) {
	return file_common_def_app_v1_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Secret_TokenEncrypt) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Secret_RefreshEncrypt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Secret_RefreshEncrypt) Reset() {
	*x = Secret_RefreshEncrypt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_def_app_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secret_RefreshEncrypt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret_RefreshEncrypt) ProtoMessage() {}

func (x *Secret_RefreshEncrypt) ProtoReflect() protoreflect.Message {
	mi := &file_common_def_app_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret_RefreshEncrypt.ProtoReflect.Descriptor instead.
func (*Secret_RefreshEncrypt) Descriptor() ([]byte, []int) {
	return file_common_def_app_v1_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Secret_RefreshEncrypt) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_common_def_app_v1_proto protoreflect.FileDescriptor

var file_common_def_app_v1_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x64, 0x65, 0x66, 0x2f, 0x61, 0x70, 0x70,
	0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6b, 0x69, 0x74, 0x2e, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x76, 0x31, 0x22,
	0x45, 0x0a, 0x03, 0x41, 0x70, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x22, 0xc4, 0x04, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x12, 0x57, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x65, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6b, 0x69,
	0x74, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x54, 0x0a, 0x0f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6b, 0x69, 0x74, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x12, 0x4a, 0x0a, 0x0b, 0x6a, 0x77, 0x74, 0x5f, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6b, 0x69, 0x74, 0x2e, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x52, 0x0a, 0x6a, 0x77, 0x74, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x54, 0x0a, 0x0f,
	0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6b, 0x69, 0x74, 0x2e, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x45, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x45, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x1a, 0x51, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x45, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x4b, 0x65, 0x79, 0x1a, 0x50, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x1a, 0x20, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x1a, 0x22, 0x0a, 0x0e, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x42, 0x2b, 0x5a,
	0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x64, 0x65, 0x6e,
	0x2f, 0x67, 0x6f, 0x2d, 0x62, 0x69, 0x7a, 0x2d, 0x6b, 0x69, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x64, 0x65, 0x66, 0x3b, 0x64, 0x65, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_common_def_app_v1_proto_rawDescOnce sync.Once
	file_common_def_app_v1_proto_rawDescData = file_common_def_app_v1_proto_rawDesc
)

func file_common_def_app_v1_proto_rawDescGZIP() []byte {
	file_common_def_app_v1_proto_rawDescOnce.Do(func() {
		file_common_def_app_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_def_app_v1_proto_rawDescData)
	})
	return file_common_def_app_v1_proto_rawDescData
}

var file_common_def_app_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_def_app_v1_proto_goTypes = []interface{}{
	(*App)(nil),                    // 0: kit.default.configv1.App
	(*Secret)(nil),                 // 1: kit.default.configv1.Secret
	(*Secret_TransferEncrypt)(nil), // 2: kit.default.configv1.Secret.TransferEncrypt
	(*Secret_ServiceEncrypt)(nil),  // 3: kit.default.configv1.Secret.ServiceEncrypt
	(*Secret_TokenEncrypt)(nil),    // 4: kit.default.configv1.Secret.TokenEncrypt
	(*Secret_RefreshEncrypt)(nil),  // 5: kit.default.configv1.Secret.RefreshEncrypt
}
var file_common_def_app_v1_proto_depIdxs = []int32{
	2, // 0: kit.default.configv1.Secret.transfer_encrypt:type_name -> kit.default.configv1.Secret.TransferEncrypt
	3, // 1: kit.default.configv1.Secret.service_encrypt:type_name -> kit.default.configv1.Secret.ServiceEncrypt
	4, // 2: kit.default.configv1.Secret.jwt_encrypt:type_name -> kit.default.configv1.Secret.TokenEncrypt
	5, // 3: kit.default.configv1.Secret.refresh_encrypt:type_name -> kit.default.configv1.Secret.RefreshEncrypt
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_def_app_v1_proto_init() }
func file_common_def_app_v1_proto_init() {
	if File_common_def_app_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_def_app_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_def_app_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Secret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_def_app_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Secret_TransferEncrypt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_def_app_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Secret_ServiceEncrypt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_def_app_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Secret_TokenEncrypt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_def_app_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Secret_RefreshEncrypt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_def_app_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_def_app_v1_proto_goTypes,
		DependencyIndexes: file_common_def_app_v1_proto_depIdxs,
		MessageInfos:      file_common_def_app_v1_proto_msgTypes,
	}.Build()
	File_common_def_app_v1_proto = out.File
	file_common_def_app_v1_proto_rawDesc = nil
	file_common_def_app_v1_proto_goTypes = nil
	file_common_def_app_v1_proto_depIdxs = nil
}
